#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80
# print "Hello World"

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' | sudo tee /var/www/html/index.html
service nginx start
